Add folder structure and naming conventions
CreoWis/next-js-launchpad pull request #22
Opened 2024-03-07 12:37 UTC by Rick799

Added folder structure and naming conventions

Fixes #19 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

# Screenshots or example output

2024-03-08 05:18 UTC, joypoddar requested changes

2024-03-11 02:33 UTC, joypoddar commented
Good job @Rick799 . There are minor changes. Take a look and resolve them

2024-03-11 02:43 UTC, joypoddar requested changes

2024-03-11 02:43 UTC, joypoddar commented on README.md
> +\***\*tests\*\***: This folder contains all 'tests'.
![image](https://github.com/CreoWis/next-js-launchpad/assets/11984043/83dec0c1-6873-4204-affa-794cb76fb4ca)
Doesn't appear right. please correct it.

2024-03-11 02:43 UTC, joypoddar commented on README.md
> +For granular level convention, read the README in specific folder.
Delete this line

2024-03-11 02:43 UTC, joypoddar commented on README.md
> +NOTE: Check specific folder README for overiding rules (if any). If there are cases where industry standards over-ride the rules mentioned above, please feel free to use them. For example convention
We no longer have README in specific folders. Re-word this sentence to accommodate the current scenario.

2024-03-11 02:43 UTC, joypoddar commented on src/config/folder.ts
> +export const FOLDER_CONFIG = [
Check if this file is being used anywhere. If not please remove it.

2024-03-11 02:43 UTC, joypoddar commented on README.md
> +    ├── components
Please put the subfolder under components

2024-03-11 02:44 UTC, joypoddar commented on src/data/README.md
> +# src/context
closed on str change

2024-03-11 02:44 UTC, joypoddar commented on src/db/README.md
> +# src/context
closed on str change

2024-03-12 02:39 UTC, joypoddar approved these changes

2024-03-12 02:51 UTC, joypoddar approved these changes

2024-03-12 02:57 UTC, atapas approved these changes

2024-03-12 02:57 UTC, merged