feat: create a launchpad homepage
CreoWis/next-js-launchpad pull request #23
Opened 2024-03-10 22:04 UTC by Rick799

Created a launchpad homepage.

Fixes #10 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

# Screenshots or example output

2024-03-11 02:27 UTC, joypoddar requested changes

2024-03-11 02:27 UTC, joypoddar commented on src/app/page.tsx
> +      <section className="w-full py-12  lg:py-14 xl:py-24 2xl:py-28">
There is a gap below the footer in the desktop view. `min-h-[94vh]` or `2xl:py-[7.4rem]` will solve the issue. Please check.

2024-03-11 02:27 UTC, joypoddar commented on src/app/page.tsx
> +    name: 'TailWind CSS',
TailWind -> Tailwind

2024-03-11 02:27 UTC, joypoddar commented on src/app/page.tsx
> +    name: 'ES Lint',
ES Lint -> ESLint

2024-03-11 02:27 UTC, joypoddar commented on src/app/page.tsx
> +  next_js: (
Remove unused icons

2024-03-11 02:27 UTC, joypoddar commented
@Rick799 Good work. Everything looks clean.

2024-03-12 02:28 UTC, atapas approved these changes

2024-03-12 02:34 UTC, joypoddar approved these changes

2024-03-12 02:38 UTC, merged

2024-03-14 04:07 UTC, atapas commented
@all-contributors please add @Rick799  for Code. please add @joypoddar  for Code.

2024-03-14 04:09 UTC, atapas commented
@all-contributors please add @joypoddar  for Code

2024-03-14 04:10 UTC, atapas commented
@all-contributors please add @chhakuli123  for Code

2024-03-14 04:12 UTC, atapas commented
@all-contributors please add @Jayakumar03 for Code

2024-03-14 04:16 UTC, atapas commented
@all-contributors please add @atapas for Review